import { Route } from '@angular/router';
import { AltBodySt } from '../altbodyst/altbodyst.model';
import { AltCateg } from '../altcateg/altcateg.model';
import { AltSegm } from '../altsegm/altsegm.model';
import { AmgCompSet } from '../amgcompset/amgcompset.model';
import { Apertura4 } from '../apertures-four/aperture-four.model';
import { ApertureOne } from '../apertures-one/aperture-one.model';
import { Apertura3 } from '../apertures-three/aperture-three.model';
import { ApertureTwo } from '../apertures-two/aperture-two.model';
import { AxleBase } from '../axlebase/axlebase.model';
import { Base } from '../base.model';
import { BodyStyle } from '../body-styles/body-style.model';
import { Bodywork } from '../bodyworks/bodywork.model';
import { CabinaCF } from '../cabinaCF/cabinaCF.model';
import { CabinaSD } from '../cabinaSD/cabinaSD.model';
import { Category } from '../categories/category.model';
import { CjdCompetitive } from '../cjdcompetitive/cjdcompetitive.model';
import { CompetitiveCjd } from '../competitivecdj/competitivecdj.model';
import { EngineCapacity } from '../enginecapacity/enginecapacity.model';
import { FuelTypes } from '../fuel/fuel.model';
import { Gear } from '../gear/gear.model';
import { Group } from '../group/group.model';
import { InternalVersion } from '../internal-versions/internal-version.model';
import { MCGTotalMkt } from '../mCGTotalMkt/mcgtotalmkt.model';
import { MotorDT } from '../motordt/motordt.model';
import { Ni } from '../nI/nI.model';
import { Power } from '../powers/power.model';
import { Rule } from '../rule/rule.model';
import { Segment } from '../segments/segment.model';
import { Subsegment } from '../subsegments/subsegment.model';
import { Traction } from '../tractions/traction.model';
import { Usage } from '../usages/usage.model';
import { Wheelbases } from '../wheelbases/wheelbases.model';
import { Source } from '../source/source.model';
import { PBT } from '../pbt/pbt.model';
import { PbtTN } from '../pbtTn/pbtTn.model';
import { Door } from '../door/door.model';
import { RelevMB } from '../relevMB/relevMb';
import { Ssegm } from '../ssegm/ssegm';
import { SegmentationAux1 } from '../segmentationAux1/segmetationaux1';
import { mercedesConfiguration } from '../mercedesConfiguration/mercedesconfiguration.model';

export class InternalVersionSegmentation extends Base {
  autoId: number | null;
  // internalVersionId: string;
  cat_InternalVersionId: string;
  mercedesVersionInternaId?: string;
  categoryId: string;
  mercedesCategoriaId?: string;
  segmentId: string;
  mercedesSegmentoId?: string;
  dischargeDate?: Date;
  description?: string;
  altBodyst?: AltBodySt;
  altBodystId?:string;
  altCateg?: AltCateg;
  altCategId?:string;
  altSegm?: AltSegm;
  altSegmId?:string;
  aMGCompSet?: AmgCompSet;
  aMGCompSetId?:string;
  apertura1?: ApertureOne;
  apertura1Id?: string;
  apertura2?: ApertureTwo;
  apertura2Id?: string;
  apertura3?: Apertura3;
  apertura3Id?: string;
  apertura4?: Apertura4;
  apertura4Id?: string;
  mercedesBodyStyle?: string;
  bodyStyleId: string;
  cabinaCF?: CabinaCF;
  cabinaCFId?:string;
  cabinaSD?: CabinaSD;
  cabinaSDId:string;
  engineCapacity?: EngineCapacity;
  engineCapacityId?: string;
  cJDCompetitive?: CjdCompetitive;
  cJDCompetitiveId?: string;
  fuelType?: FuelTypes;
  fuelTypeId?: string;
  competitiveCJD?: CompetitiveCjd;
  competitiveCJDId?: string;
  mercedesConfiguration?: mercedesConfiguration;
  mercedesConfigurationId?: string;
  bodyworkId: string;
  wheelbase?: Wheelbases;
  wheelBaseId?: string;
  axleBase?: AxleBase;
  axleBaseId?: string;
  group?: Group;
  groupId?: string;
  gears?: Gear;
  gearsId?: string;
  mcgTotalMkt?: MCGTotalMkt;
  mcgTotalMktId?: string;
  motorDT?: MotorDT;
  motorDTId?: string;
  nI?: Ni;
  nIId?: string;
  catRule?: Rule;
  catRuleId?: string;
  source?: Source;
  sourceId?: string;
  mercedesPBT?: PBT;
  mercedesPBTId?: string;
  subSegmentId: string;
  subsegment: string;
  pbT_TN?: PbtTN;
  pbT_TNId?: string;
  mercedesPower?: string;
  powerId: string;
  doors?: Door;
  doorsId?:string;
  relevMB?: RelevMB;
  relevMBId?: string;
  sSegm?: Ssegm;
  sSegmId?: string;
  mercedesTraction?: string;
  tractionId: string;
  mercedesUsage?: string;
  usageId: string;
  segmentationAux1?: SegmentationAux1;
  segmentationAux2?: string;
  segmentationAux3?: string;
  segmentationAux4?: string;
  segmentationAux5?: string;
  segmentationAux1Id?: string;
  segmentationAux2Id?: string;
  segmentationAux3Id?: string;
  segmentationAux4Id?: string;
  segmentationAux5Id?: string;
  constructor() {
    super();
    this.autoId = 0;
    // this.internalVersionId = '';
    this.cat_InternalVersionId = ''
    this.categoryId = '';
    this.segmentId = '';
    this.bodyStyleId = '';
    this.bodyworkId = '';
    this.subSegmentId = '';
    this.powerId = '';
    this.tractionId = '';
    this.usageId = '';
    this.cabinaSDId='';
    this.subsegment='';
  }
}
