import { AltBodySt } from '../altbodyst/altbodyst.model';
import { AltCateg } from '../altcateg/altcateg.model';
import { AltSegm } from '../altsegm/altsegm.model';
import { AmgCompSet } from '../amgcompset/amgcompset.model';
import { Apertura4 } from '../apertures-four/aperture-four.model';
import { ApertureOne } from '../apertures-one/aperture-one.model';
import { Apertura3 } from '../apertures-three/aperture-three.model';
import { ApertureTwo } from '../apertures-two/aperture-two.model';
import { AxleBase } from '../axlebase/axlebase.model';
import { BodyStyle } from '../body-styles/body-style.model';
import { Bodywork } from '../bodyworks/bodywork.model';
import { CabinaCF } from '../cabinaCF/cabinaCF.model';
import { CabinaSD } from '../cabinaSD/cabinaSD.model';
import { CatInternalVersion } from '../cat-internal-versions/cat-internal-versions.model';
import { Category } from '../categories/category.model';
import { CjdCompetitive } from '../cjdcompetitive/cjdcompetitive.model';
import { CompetitiveCjd } from '../competitivecdj/competitivecdj.model';
import { Door } from '../door/door.model';
import { EngineCapacity } from '../enginecapacity/enginecapacity.model';
import { FuelTypes } from '../fuel/fuel.model';
import { Gear } from '../gear/gear.model';
import { Group } from '../group/group.model';
import { InternalVersion } from '../internal-versions/internal-version.model';
import { MCGTotalMkt } from '../mCGTotalMkt/mcgtotalmkt.model';
import { mercedesConfiguration } from '../mercedesConfiguration/mercedesconfiguration.model';
import { MotorDT } from '../motordt/motordt.model';
import { Ni } from '../nI/nI.model';
import { PBT } from '../pbt/pbt.model';
import { PbtTN } from '../pbtTn/pbtTn.model';
import { Power } from '../powers/power.model';
import { RelevMB } from '../relevMB/relevMb';
import { Rule } from '../rule/rule.model';
import { SegmentationAux1 } from '../segmentationAux1/segmetationaux1';
import { Segment } from '../segments/segment.model';
import { Source } from '../source/source.model';
import { Ssegm } from '../ssegm/ssegm';
import { Subsegment } from '../subsegments/subsegment.model';
import { Traction } from '../tractions/traction.model';
import { Usage } from '../usages/usage.model';
import { Wheelbases } from '../wheelbases/wheelbases.model';

export class InternalVersionSegmentationCatalogs {
  internalVersions: CatInternalVersion[];
  categories: Category[];
  segments: Segment[];
  bodyStyles: BodyStyle[];
  bodyworks: Bodywork[];
  subsegments: Subsegment[];
  usages: Usage[];
  tractions: Traction[];
  fueltypes:FuelTypes[];
  gears:Gear[];
  cabinSDs:CabinaSD[];
  powers: Power[];
  wheelbases:Wheelbases[];
  axlebases:AxleBase[];
  doors:Door[];
  mcgTotalMkts:MCGTotalMkt[];
  motorDTs:MotorDT[];
  catRules:Rule[];
  sources:Source[];
  pbts:PBT[];
  pbttns:PbtTN[];
  altBodysts:AltBodySt[];
  altCategs:AltCateg[];
  altSegms:AltSegm[];
  amgCompsets:AmgCompSet[];
  aperturesOne:ApertureOne[];
  aperturesTwo:ApertureTwo[];
  aperturesThree:Apertura3[];
  aperturesFour:Apertura4[];
  cjdCompetitives:CjdCompetitive[];
  engineCapacitys:EngineCapacity[];
  cabinCFs:CabinaCF[];
  groups:Group[];
  competitiveCJDs:CompetitiveCjd[];
  nis:Ni[];
  ssegms:Ssegm[];
  relevMBs:RelevMB[];
  segmentationAux1s:SegmentationAux1[];
  configurations:mercedesConfiguration[];

  constructor() {
    this.internalVersions = [];
    this.categories = [];
    this.segments = [];
    this.bodyStyles = [];
    this.bodyworks = [];
    this.subsegments = [];
    this.usages = [];
    this.tractions = [];
    this.fueltypes=[];
    this.cabinSDs=[];
    this.powers = [];
    this.wheelbases=[];
    this.axlebases=[];
    this.doors=[];
    this.mcgTotalMkts=[];
    this.motorDTs=[];
    this.catRules=[];
    this.sources=[];
    this.pbts=[];
    this.pbttns=[];
    this.altBodysts=[];
    this.altCategs=[];
    this.altSegms=[];
    this.amgCompsets=[];
    this.aperturesOne=[];
    this.aperturesTwo=[];
    this.aperturesThree=[];
    this.aperturesFour=[];
    this.cabinCFs=[];
    this.engineCapacitys=[];
    this.cjdCompetitives=[];
    this.groups=[];
    this.competitiveCJDs=[];
    this.segmentationAux1s=[];
    this.relevMBs=[];
    this.ssegms=[];
    this.nis=[];
    this.gears=[];
    this.configurations=[];
  }
}
