export interface InternalVersionSegmentationCreateDto {
  id: string;
  // internalVersionId: string;
  cat_InternalVersion:string
  cat_InternalVersionId:string
  mercedesVersionInternaId?: string;
  categoryId: string;
  mercedesCategoriaId?: string;
  segmentId: string;
  mercedesSegmentoId?: string;
  dischargeDate?: Date;
  description?: string;
  altbodyst?: string;
  altBodystId?:string;
  altCateg?: string;
  altCategId?:string;
  altsegm?: string;
  altsegmId?:string;
  aMGCompSet?: string;
  amgCompSetId?:string;
  apertura1?: string;
  apertura1Id?: string;
  apertura2?: string;
  apertura2Id?: string;
  apertura3?: string;
  apertura3Id?: string;
  apertura4?: string;
  apertura4Id?: string;
  mercedesBodyStyle?: string;
  bodyStyleId: string;
  cabinaCF?: string;
  cabinaCFId?:string;
  cabinaSD?: string;
  cabinaSDId:string;
  engineCapacity?: string;
  engineCapacityId?: string;
  cJDCompetitive?: string;
  cJDCompetitiveId?: string;
  fuelType?: string;
  fuelTypeId?: string;
  competitiveCJD?: string;
  competitiveCJDId?: string;
  mercedesConfiguration?: string;
  mercedesConfigurationId?: string;
  bodyworkId: string;
  wheelbase?: string;
  wheelBaseId?: string;
  axleBase?: string;
  axleBaseId?: string;
  group?: string;
  groupId?: string;
  gears?: string;
  gearsId?: string;
  mCGTotalMkt?: string;
  mCGTotalMktId?: string;
  motorDT?: string;
  motorDTId?: string;
  nI?: string;
  nIId?: string;
  catRule?: string;
  catRuleId?: string;
  source?: string;
  sourceId?: string;
  mercedesPBT?: string;
  mercedesPBTId?: string;
  subSegmentId: string;
  pBT_TN?: string;
  pBT_TNId?: string;
  mercedesPower?: string;
  powerId: string;
  doors?: string;
  doorsId?:string;
  relevMB?: string;
  relevMBId?: string;
  sSegm?: string;
  sSegmId?: string;
  mercedesTraction?: string;
  tractionId: string;
  mercedesUsage?: string;
  usageId: string;
  segmentationAux1?: string;
  segmentationAux2?: string;
  segmentationAux3?: string;
  segmentationAux4?: string;
  segmentationAux5?: string;
  segmentationAux1Id?: string;
  segmentationAux2Id?: string;
  segmentationAux3Id?: string;
  segmentationAux4Id?: string;
  segmentationAux5Id?: string;
}
