import { Base } from '../base.model';
import { Category } from '../categories/category.model';
import { File } from '../files/file.model';
import { Grado } from '../grados/grado.model';
import { StatePatenta } from '../state-patentas/state-patenta.model';
import { VehicleType } from '../vehicle-types/vehicle-type.model';

export class OdsWholesale extends Base {
  autoId: number | null;
  yearMonth: string;
  codBrand: string;
  brand: string;
  codModel: string;
  model: string;
  codTrademark: string;
  trademark: string;
  gradoId: string;
  grado?: Grado | null;
  doorsQty: string;
  engine: string;
  motorType: string;
  fuelType: string;
  power: string;
  powerUnit: string;
  mercedesVehicleType: string;
  vehicleTypeId: string;
  vehicleType?: VehicleType | null;
  traction: string;
  gearsQty: string;
  transmissionType: string;
  axleQty: string;
  weight: string;
  loadCapacity: string;
  mercedesCategory: string;
  categoryId: string;
  category?: Category | null;
  origin: string;
  initialStock: string;
  import_ProdMonth: string;
  import_ProdAccum: string;
  monthlySale: string;
  monthlyAccum: string;
  exportMonthly: string;
  exportAccum: string;
  savingSystemMonthly: string;
  savingSystemAccum: string;
  finalStock: string;
  noOkStock: string;
  statePatentaId: string;
  statePatenta?: StatePatenta | null;
  fileId: string;
  file?: File | null;
  errores?: string;
  errorName?: string;

  constructor() {
    super();
    this.autoId = 0;
    this.yearMonth = '';
    this.codBrand = '';
    this.brand = '';
    this.codModel = '';
    this.model = '';
    this.codTrademark = '';
    this.trademark = '';
    this.gradoId = '';
    this.doorsQty = '';
    this.engine = '';
    this.motorType = '';
    this.fuelType = '';
    this.power = '';
    this.powerUnit = '';
    this.mercedesVehicleType = '';
    this.vehicleTypeId = '';
    this.traction = '';
    this.gearsQty = '';
    this.transmissionType = '';
    this.axleQty = '';
    this.weight = '';
    this.loadCapacity = '';
    this.mercedesCategory = '';
    this.categoryId = '';
    this.origin = '';
    this.initialStock = '';
    this.import_ProdMonth = '';
    this.import_ProdAccum = '';
    this.monthlySale = '';
    this.monthlyAccum = '';
    this.exportMonthly = '';
    this.exportAccum = '';
    this.savingSystemMonthly = '';
    this.savingSystemAccum = '';
    this.finalStock = '';
    this.noOkStock = '';
    this.statePatentaId = '';
    this.fileId = '';
  }
}
