import { Base } from '../base.model';
import { Brand } from '../brands/brand.model';
import { CarModel } from '../car-models/car-model.model';
import { Closure } from '../closures/closure.model';
import { Department } from '../departments/department.model';
import { Factory } from '../factories/factory.model';
import { File } from '../files/file.model';
import { Owner } from '../owners/owner.model';
import { Province } from '../provinces/province.model';
import { RegSec } from '../reg-secs/reg-sec.model';
import { StatePatenta } from '../state-patentas/state-patenta.model';
import { VehicleType } from '../vehicle-types/vehicle-type.model';

export class Patenting extends Base {
  autoId?: number | null;
  ownerId: string;
  owner?: Owner | null;
  factoryId: string;
  factory?: Factory | null;
  carModelId: string;
  carModel?: CarModel | null;
  closureId: string;
  closure?: Closure | null;
  plate: string;
  motor: string;
  chasis: string;
  ofmm: string;
  origen: string;
  fmm_mtm: string;
  calDay: string;
  calMonth: string;
  calYear: string;
  nroRegistro: string;
  direccion: string;
  codigoPostal: string;
  anio: string;
  auto: string;
  paisFabrica: string;
  paisProced: string;
  peso: string;
  cantPatentamiento: number;
  fechaCarga?: Date;
  ofmm_error: string;
  es_duplicado: boolean;
  regSecId: string;
  regSec?: RegSec | null;
  provinceId: string;
  province?: Province | null;
  departmentId: string;
  department?: Department | null;
  locationId: string;
  location?: Location | null;
  brandId: string;
  brand?: Brand | null;
  statePatentaId: string;
  statePatenta?: StatePatenta | null;
  vehicleTypeId: string;
  vehicleType?: VehicleType | null;
  fileId: string;
  file?: File | null;
  fechInsc?: Date;
  fabricaPat?: string;
  marcaPat?: string;
  modeloPat?: string;
  fabrica_D?: string;
  marca_D?: string;
  modelo_D?: string;
  tipo_D?: string;

  constructor() {
    super();
    this.carModelId = '';
    this.closureId = '';
    this.plate = '';
    this.motor = '';
    this.chasis = '';
    this.ofmm = '';
    this.origen = '';
    this.fmm_mtm = '';
    this.calDay = '';
    this.calMonth = '';
    this.calYear = '';
    this.nroRegistro = '';
    this.direccion = '';
    this.codigoPostal = '';
    this.anio = '';
    this.auto = '';
    this.paisFabrica = '';
    this.paisProced = '';
    this.peso = '';
    this.cantPatentamiento = 1;
    this.ofmm_error = '';
    this.es_duplicado = false;
    this.regSecId = '';
    this.provinceId = '';
    this.departmentId = '';
    this.locationId = '';
    this.brandId = '';
    this.ownerId = '';
    this.factoryId = '';
    this.brandId = '';
    this.vehicleTypeId = '';
    this.fileId = '';
    this.statePatentaId = '';
  }
}
